[style.description]
foreground = "blue"
underline = false
bold = true
italic = false

[style.command_name]
foreground = "green"
underline = false
bold = true
italic = false

[style.example_text]
foreground = "blue"
underline = false
bold = false
italic = false

[style.example_code]
foreground = "yellow"
underline = false
bold = false
italic = false

[style.example_variable]
foreground = "red"
underline = true
bold = false
italic = false

[display]
compact = false
use_pager = false

[updates]
auto_update = true
auto_update_interval_hours = 720

[directories]
custom_pages_dir = "/var/home/epoy/.local/share/tealdeer/pages/"
